package client

import (
	"encoding/json"
	"testing"
)

func TestWord(t *testing.T) {
	bodyStr := `
{
  "ok": 1,
  "data": {
    "hotgov": {
      "note": "#文明之美看东方#",
      "is_hot": 1,
      "name": "#文明之美看东方#",
      "url": "http://weibo.com/2286908003/LD0mm542B",
      "word": "#文明之美看东方#",
      "is_gov": 1,
      "icon_desc": "热",
      "icon_desc_color": "#ff9406",
      "mid": "4792961781207177",
      "topic_flag": 1,
      "small_icon_desc": "热",
      "small_icon_desc_color": "#ff9406"
    },
    "realtime": [
      {
        "note": "同事称王冰冰朋友圈无官宣图文",
        "ad_info": "",
        "category": "艺人",
        "num": 2576715,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "4793378154484586",
        "word": "同事称王冰冰朋友圈无官宣图文",
        "fun_word": 1,
        "flag": 1,
        "onboard_time": 1658327316,
        "raw_hot": 2576715,
        "emoticon": "",
        "word_scheme": "#同事称王冰冰朋友圈无官宣图文#",
        "star_name": {},
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "Entertainment",
        "icon_desc": "新",
        "realpos": 1,
        "icon_desc_color": "#ff3852",
        "topic_flag": 1,
        "small_icon_desc": "新",
        "star_word": 1,
        "rank": 0
      },
      {
        "note": "小肚子不扁下去都难了",
        "ad_info": "",
        "category": "体育",
        "num": 2055752,
        "expand": 0,
        "small_icon_desc_color": "#f86400",
        "mid": "4793433568318234",
        "word": "小肚子不扁下去都难了",
        "fun_word": 0,
        "flag": 16,
        "onboard_time": 1658319991,
        "raw_hot": 2055752,
        "emoticon": "",
        "is_fei": 1,
        "star_name": {},
        "subject_label": "",
        "word_scheme": "#小肚子不扁下去都难了#",
        "subject_querys": "",
        "label_name": "沸",
        "channel_type": "",
        "icon_desc": "沸",
        "realpos": 2,
        "icon_desc_color": "#f86400",
        "topic_flag": 1,
        "small_icon_desc": "沸",
        "star_word": 0,
        "rank": 1
      },
      {
        "note": "查处利用网红儿童牟利行为",
        "ad_info": "",
        "category": "社会新闻",
        "num": 2050780,
        "expand": 0,
        "mid": "4793343035048703",
        "word": "查处利用网红儿童牟利行为",
        "emoticon": "",
        "label_name": "",
        "raw_hot": 72640,
        "subject_label": "",
        "flag": 0,
        "subject_querys": "",
        "star_name": {},
        "channel_type": "",
        "word_scheme": "#查处利用网红儿童牟利行为#",
        "realpos": 3,
        "onboard_time": 1658309614,
        "topic_flag": 1,
        "fun_word": 0,
        "star_word": 0,
        "rank": 2
      },
      {
        "note": "难看",
        "is_hot": 1,
        "category": "影视",
        "num": 2050443,
        "expand": 0,
        "small_icon_desc_color": "#ff9406",
        "fun_word": 1,
        "mid": "4793392380772715",
        "word": "难看",
        "ad_info": "",
        "flag": 2,
        "onboard_time": 1658320836,
        "flag_desc": "剧集",
        "emoticon": "",
        "star_name": {},
        "word_scheme": "难看",
        "subject_label": "剧集",
        "raw_hot": 2050443,
        "subject_querys": "剧集|沉香如屑",
        "label_name": "热",
        "channel_type": "Entertainment",
        "icon_desc": "热",
        "realpos": 4,
        "icon_desc_color": "#ff9406",
        "topic_flag": 0,
        "small_icon_desc": "热",
        "star_word": 0,
        "rank": 3
      },
      {
        "note": "河南36岁女子升级当奶奶",
        "ad_info": "",
        "category": "社会新闻",
        "num": 1793620,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "4793430867444906",
        "word": "河南36岁女子升级当奶奶",
        "fun_word": 0,
        "flag": 1,
        "onboard_time": 1658327197,
        "raw_hot": 1793620,
        "emoticon": "",
        "word_scheme": "#河南36岁女子升级当奶奶#",
        "star_name": {},
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "",
        "icon_desc": "新",
        "realpos": 5,
        "icon_desc_color": "#ff3852",
        "topic_flag": 1,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 4
      },
      {
        "note": "中国男篮vs黎巴嫩男篮 裁判",
        "ad_info": "",
        "category": "体育",
        "num": 1738126,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "4793421534859159",
        "word": "中国男篮vs黎巴嫩男篮 裁判",
        "fun_word": 0,
        "flag": 1,
        "onboard_time": 1658325393,
        "raw_hot": 1738126,
        "emoticon": "",
        "word_scheme": "中国男篮vs黎巴嫩男篮 裁判",
        "star_name": {},
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "",
        "icon_desc": "新",
        "realpos": 6,
        "icon_desc_color": "#ff3852",
        "topic_flag": 0,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 5
      },
      {
        "poi": 6,
        "sort": 3,
        "id": 160320,
        "ad_channel": 1,
        "word": "王嘉尔钟楚曦送芍药",
        "is_ad": 1,
        "emoticon": "[阿玛尼芍药]",
        "is_abtest": 0,
        "star_name": {},
        "logo": "",
        "icon_desc": "商",
        "icon_desc_color": "#00b7ee",
        "topic_ad": 1,
        "small_icon_desc": "商",
        "small_icon_desc_color": "#00b7ee",
        "note": "王嘉尔钟楚曦送芍药",
        "monitor": {},
        "num": 1728434,
        "end_time": 1658332799,
        "is_star": 1,
        "is_topic": 1,
        "mobile_icon": {
          "height": 24,
          "hotband": "https://simg.s.weibo.com/20210623_jian.png",
          "band": "https://simg.s.weibo.com/20210623_jian.png",
          "finder": "https://simg.s.weibo.com/20210623_jian_small.png",
          "width": 24
        },
        "icon": "https://simg.s.weibo.com/20180814113351_jian_28_0813.png",
        "pc_icon": {
          "hotband_desc_color": "#00b7ee",
          "band_desc_color": "#00b7ee",
          "finder_desc_color": "#00b7ee",
          "band_desc": "商",
          "finder_desc": "商",
          "hotband_desc": "商"
        },
        "updated_time": "1658248267",
        "ad_type": "商业投放",
        "icon_type": "jian",
        "icon_width": 24,
        "icon_height": 24,
        "monitors": {
          "app": [
            {
              "third_party_click": "https://e.cn.miaozhen.com/r?k=2309277&p=8CqFt&dx=__IPDX__&rt=2&pro=s&ns=__IP__&ni=__IESID__&v=__LOC__&xa=__ADPLATFORM__&tr=__REQUESTID__&na=__SUID__&vo=34f1ace29&vr=2&o=https%3A%2F%2Ftrace.rtbasia.com%2Ftkp%3Frta_k%3DaAySnuVIBG%26utm_campaign%3D_rtc_f406c7ded09ed9da%26utm_source%3Dweibo%26utm_content%3DWeiboChaojiDashichuang%26utm_medium%3D6428_2_0%26utm_term%3DDisplay%26device%3DMobile%26imei%3D__IMEI__%26mac%3D__MAC__%26mac1%3D__MAC1__%26idfa%3D__IDFA__%26uid%3D__UID__%26androidid%3D__ANDROIDID__%26oaid%3D__OAID__%26custid1%3D__CUSTID1__%26custid2%3D__CUSTID2__%26os%3D__OS__%26ua%3D__UA__%26ts%3D__TS__%26clientip%3D__IP__%26sg%3D6048f5b562ff6e19dca9403a0b9996f3%26ord%3D1657687738208",
              "third_party_show": "",
              "type": "C2S"
            },
            {
              "third_party_click": "",
              "third_party_show": "",
              "type": "C2S"
            }
          ],
          "pc": [
            {
              "pc_show": "",
              "type": "C2S",
              "pc_click": "https://e.cn.miaozhen.com/r?k=2309277&p=8CqFt&dx=__IPDX__&rt=2&pro=s&ns=__IP__&ni=__IESID__&v=__LOC__&xa=__ADPLATFORM__&tr=__REQUESTID__&na=__SUID__&vo=34f1ace29&vr=2&o=https%3A%2F%2Ftrace.rtbasia.com%2Ftkp%3Frta_k%3DaAySnuVIBG%26utm_campaign%3D_rtc_f406c7ded09ed9da%26utm_source%3Dweibo%26utm_content%3DWeiboChaojiDashichuang%26utm_medium%3D6428_2_0%26utm_term%3DDisplay%26device%3DMobile%26imei%3D__IMEI__%26mac%3D__MAC__%26mac1%3D__MAC1__%26idfa%3D__IDFA__%26uid%3D__UID__%26androidid%3D__ANDROIDID__%26oaid%3D__OAID__%26custid1%3D__CUSTID1__%26custid2%3D__CUSTID2__%26os%3D__OS__%26ua%3D__UA__%26ts%3D__TS__%26clientip%3D__IP__%26sg%3D6048f5b562ff6e19dca9403a0b9996f3%26ord%3D1657687738208"
            },
            {
              "pc_show": "",
              "type": "C2S",
              "pc_click": ""
            }
          ]
        },
        "dot_icon": 1,
        "topic_flag": 1,
        "start_time": 1658246400,
        "name": "#王嘉尔钟楚曦送芍药#",
        "forbidden": {},
        "rank": 5
      },
      {
        "note": "易烊千玺同时提名百花奖男主男配",
        "ad_info": "",
        "category": "影视",
        "num": 1576585,
        "expand": 0,
        "small_icon_desc_color": "#f86400",
        "fun_word": 1,
        "mid": "4793343214883572",
        "word": "易烊千玺同时提名百花奖男主男配",
        "flag": 16,
        "onboard_time": 1658303612,
        "flag_desc": "盛典",
        "is_fei": 1,
        "emoticon": "",
        "star_name": [
          "易烊千玺"
        ],
        "word_scheme": "#易烊千玺同时提名百花奖男主男配#",
        "subject_label": "盛典",
        "raw_hot": 1576585,
        "subject_querys": "盛典|百花奖",
        "label_name": "沸",
        "channel_type": "Entertainment",
        "icon_desc": "沸",
        "realpos": 7,
        "icon_desc_color": "#f86400",
        "topic_flag": 1,
        "small_icon_desc": "沸",
        "star_word": 0,
        "rank": 6
      },
      {
        "note": "中国男篮失误",
        "ad_info": "",
        "category": "体育",
        "num": 1462725,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "4793423397131546",
        "word": "中国男篮失误",
        "fun_word": 0,
        "flag": 1,
        "onboard_time": 1658325035,
        "raw_hot": 1462725,
        "emoticon": "",
        "word_scheme": "#中国男篮失误#",
        "star_name": {},
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "",
        "icon_desc": "新",
        "realpos": 8,
        "icon_desc_color": "#ff3852",
        "topic_flag": 1,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 7
      },
      {
        "note": "中国男篮无缘四强",
        "ad_info": "",
        "category": "体育",
        "num": 1202157,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "4793440405558240",
        "word": "中国男篮无缘四强",
        "fun_word": 0,
        "flag": 1,
        "onboard_time": 1658329179,
        "raw_hot": 1202157,
        "emoticon": "",
        "word_scheme": "中国男篮无缘四强",
        "star_name": {},
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "",
        "icon_desc": "新",
        "realpos": 9,
        "icon_desc_color": "#ff3852",
        "topic_flag": 0,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 8
      },
      {
        "note": "植物人丈夫被妻子唤醒说谢谢",
        "ad_info": "",
        "category": "社会新闻",
        "num": 1187702,
        "expand": 0,
        "mid": "4793428573164009",
        "word": "植物人丈夫被妻子唤醒说谢谢",
        "emoticon": "",
        "label_name": "",
        "raw_hot": 857915,
        "subject_label": "",
        "flag": 0,
        "subject_querys": "",
        "star_name": {},
        "channel_type": "",
        "word_scheme": "#植物人丈夫被妻子唤醒说谢谢#",
        "realpos": 10,
        "onboard_time": 1658322995,
        "topic_flag": 1,
        "fun_word": 0,
        "star_word": 0,
        "rank": 9
      },
      {
        "note": "希林娜依高 抄袭",
        "ad_info": "",
        "category": "艺人",
        "num": 1186422,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "4793434953745601",
        "word": "希林娜依高 抄袭",
        "fun_word": 1,
        "flag": 1,
        "onboard_time": 1658328757,
        "raw_hot": 3373833,
        "emoticon": "",
        "word_scheme": "希林娜依高 抄袭",
        "star_name": [
          "希林娜依高"
        ],
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "Entertainment",
        "icon_desc": "新",
        "realpos": 11,
        "icon_desc_color": "#ff3852",
        "topic_flag": 0,
        "small_icon_desc": "新",
        "star_word": 1,
        "rank": 10
      },
      {
        "note": "月升沧海",
        "ad_info": "",
        "category": "影视",
        "num": 1182658,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "fun_word": 1,
        "mid": "4793418133798920",
        "word": "月升沧海",
        "flag": 1,
        "onboard_time": 1658326112,
        "flag_desc": "剧集",
        "word_scheme": "月升沧海",
        "emoticon": "[泪]",
        "star_name": {},
        "is_new": 1,
        "subject_label": "剧集",
        "raw_hot": 1182658,
        "subject_querys": "剧集|星汉灿烂",
        "label_name": "新",
        "channel_type": "Entertainment",
        "icon_desc": "新",
        "realpos": 12,
        "icon_desc_color": "#ff3852",
        "topic_flag": 0,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 11
      },
      {
        "note": "王冰冰 徐嘉余",
        "is_hot": 1,
        "category": "体育,艺人",
        "num": 1181764,
        "expand": 0,
        "small_icon_desc_color": "#ff9406",
        "mid": "4793349742265391",
        "word": "王冰冰 徐嘉余",
        "fun_word": 1,
        "ad_info": "",
        "flag": 2,
        "onboard_time": 1658302408,
        "emoticon": "[泪]",
        "raw_hot": 1181764,
        "star_name": {},
        "subject_label": "",
        "word_scheme": "王冰冰 徐嘉余",
        "subject_querys": "",
        "label_name": "热",
        "channel_type": "Entertainment",
        "icon_desc": "热",
        "realpos": 13,
        "icon_desc_color": "#ff9406",
        "topic_flag": 0,
        "small_icon_desc": "热",
        "star_word": 1,
        "rank": 12
      },
      {
        "note": "徐杰三分",
        "ad_info": "",
        "category": "体育",
        "num": 1088216,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "4793435846875160",
        "word": "徐杰三分",
        "fun_word": 0,
        "flag": 1,
        "onboard_time": 1658328217,
        "raw_hot": 1088216,
        "emoticon": "",
        "word_scheme": "#徐杰三分#",
        "star_name": {},
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "",
        "icon_desc": "新",
        "realpos": 14,
        "icon_desc_color": "#ff3852",
        "topic_flag": 1,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 13
      },
      {
        "pid": 0,
        "id": 160432,
        "ad_channel": 3,
        "mid": "",
        "word": "小伙被困火场绝望中等来消防员",
        "source": 27,
        "emoticon": "",
        "name": "#小伙被困火场绝望中等来消防员#",
        "subject_label": "",
        "subject_querys": "",
        "star_name": {},
        "channel_type": "",
        "realpos": 15,
        "onboard_time": 1658329242,
        "topic_flag": 1,
        "status": 1,
        "word_scheme": "#小伙被困火场绝望中等来消防员#",
        "note": "小伙被困火场绝望中等来消防员",
        "ad_info": {
          "is_control": 0,
          "zone_id": "",
          "name": "#小伙被困火场绝望中等来消防员#",
          "material": {},
          "pid": 0,
          "id": 160432,
          "monitors": {
            "app": {},
            "pc": {}
          },
          "start_time": 1658329200,
          "ad_channel": 3,
          "status": 1,
          "end_time": 1658332800,
          "topic_flag": 1,
          "source": 27,
          "monitor": {}
        },
        "category": "社会新闻",
        "monitor": {},
        "num": 1056448,
        "end_time": 1658332800,
        "expand": 0,
        "is_control": 0,
        "zone_id": "",
        "material": {},
        "monitors": {
          "app": {},
          "pc": {}
        },
        "star_word": 0,
        "flag": 0,
        "start_time": 1658329200,
        "label_name": "",
        "raw_hot": 40141,
        "fun_word": 0,
        "rank": 14
      },
      {
        "note": "还得是周琦",
        "ad_info": "",
        "category": "体育",
        "num": 1045861,
        "expand": 0,
        "mid": "4793415386799709",
        "word": "还得是周琦",
        "emoticon": "",
        "label_name": "",
        "raw_hot": 1045861,
        "subject_label": "",
        "flag": 0,
        "subject_querys": "",
        "star_name": {},
        "channel_type": "",
        "word_scheme": "#还得是周琦#",
        "realpos": 16,
        "onboard_time": 1658324072,
        "topic_flag": 1,
        "fun_word": 0,
        "star_word": 0,
        "rank": 15
      },
      {
        "note": "微信打开时支持消息通知横幅",
        "ad_info": "",
        "category": "科技",
        "num": 798437,
        "expand": 0,
        "mid": "4793399258909132",
        "word": "微信打开时支持消息通知横幅",
        "emoticon": "",
        "label_name": "",
        "raw_hot": 798437,
        "subject_label": "",
        "flag": 0,
        "subject_querys": "",
        "star_name": {},
        "channel_type": "",
        "word_scheme": "#微信打开时支持消息通知横幅#",
        "realpos": 17,
        "onboard_time": 1658318851,
        "topic_flag": 1,
        "fun_word": 0,
        "star_word": 0,
        "rank": 16
      },
      {
        "note": "乌克兰核电站遭无人机袭击",
        "ad_info": "",
        "category": "军事,国外要闻",
        "num": 747245,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "4793435158484180",
        "word": "乌克兰核电站遭无人机袭击",
        "fun_word": 0,
        "flag": 1,
        "onboard_time": 1658325035,
        "raw_hot": 747245,
        "emoticon": "",
        "word_scheme": "#乌克兰核电站遭无人机袭击#",
        "star_name": {},
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "",
        "icon_desc": "新",
        "realpos": 18,
        "icon_desc_color": "#ff3852",
        "topic_flag": 1,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 17
      },
      {
        "note": "孙铭徽 传球",
        "ad_info": "",
        "category": "体育",
        "num": 706429,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "4793423607630942",
        "word": "孙铭徽 传球",
        "fun_word": 0,
        "flag": 1,
        "onboard_time": 1658326355,
        "raw_hot": 706429,
        "emoticon": "",
        "word_scheme": "孙铭徽 传球",
        "star_name": {},
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "",
        "icon_desc": "新",
        "realpos": 19,
        "icon_desc_color": "#ff3852",
        "topic_flag": 0,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 18
      },
      {
        "note": "国足0比3韩国",
        "ad_info": "",
        "category": "体育",
        "num": 609568,
        "expand": 0,
        "mid": "4793396331808237",
        "word": "国足0比3韩国",
        "emoticon": "",
        "label_name": "",
        "raw_hot": 609568,
        "subject_label": "",
        "flag": 0,
        "subject_querys": "",
        "star_name": {},
        "channel_type": "",
        "word_scheme": "#国足0比3韩国#",
        "realpos": 20,
        "onboard_time": 1658318132,
        "topic_flag": 1,
        "fun_word": 0,
        "star_word": 0,
        "rank": 19
      },
      {
        "note": "拉宏桑 山城小栗旬",
        "ad_info": "",
        "category": "综艺",
        "num": 599476,
        "expand": 0,
        "mid": "4793267016702645",
        "word": "拉宏桑 山城小栗旬",
        "label_name": "",
        "emoticon": "",
        "raw_hot": 936923,
        "flag": 0,
        "flag_desc": "综艺",
        "fun_word": 1,
        "subject_querys": "综艺|向前冲",
        "star_name": {},
        "channel_type": "Entertainment",
        "word_scheme": "拉宏桑 山城小栗旬",
        "realpos": 21,
        "onboard_time": 1658320893,
        "topic_flag": 0,
        "subject_label": "综艺",
        "star_word": 0,
        "rank": 20
      },
      {
        "note": "幸福生二胎了",
        "ad_info": "",
        "category": "影视",
        "num": 582801,
        "expand": 0,
        "mid": "4793402698240742",
        "word": "幸福生二胎了",
        "label_name": "",
        "emoticon": "",
        "raw_hot": 681880,
        "flag": 0,
        "flag_desc": "剧集",
        "fun_word": 1,
        "subject_querys": "剧集|幸福到万家",
        "star_name": {},
        "channel_type": "Entertainment",
        "word_scheme": "#幸福生二胎了#",
        "realpos": 22,
        "onboard_time": 1658318731,
        "topic_flag": 1,
        "subject_label": "剧集",
        "star_word": 0,
        "rank": 21
      },
      {
        "note": "星汉灿烂预告27",
        "ad_info": "",
        "category": "影视",
        "num": 582137,
        "expand": 0,
        "mid": "4793426456086195",
        "word": "星汉灿烂预告27",
        "label_name": "",
        "emoticon": "[泪]",
        "raw_hot": 676442,
        "flag": 0,
        "flag_desc": "剧集",
        "fun_word": 1,
        "subject_querys": "剧集|星汉灿烂",
        "star_name": {},
        "channel_type": "Entertainment",
        "word_scheme": "星汉灿烂预告27",
        "realpos": 23,
        "onboard_time": 1658322213,
        "topic_flag": 0,
        "subject_label": "剧集",
        "star_word": 0,
        "rank": 22
      },
      {
        "note": "中国男篮不敌黎巴嫩男篮",
        "ad_info": "",
        "category": "体育",
        "num": 546574,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "",
        "word": "中国男篮不敌黎巴嫩男篮",
        "fun_word": 0,
        "flag": 1,
        "onboard_time": 1658329477,
        "raw_hot": 546574,
        "emoticon": "",
        "word_scheme": "#中国男篮不敌黎巴嫩男篮#",
        "star_name": {},
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "",
        "icon_desc": "新",
        "realpos": 24,
        "icon_desc_color": "#ff3852",
        "topic_flag": 1,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 23
      },
      {
        "note": "想念郭艾伦",
        "ad_info": "",
        "category": "体育",
        "num": 524990,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "4793426782457276",
        "word": "想念郭艾伦",
        "fun_word": 0,
        "flag": 1,
        "onboard_time": 1658328942,
        "raw_hot": 524990,
        "emoticon": "",
        "word_scheme": "想念郭艾伦",
        "star_name": {},
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "",
        "icon_desc": "新",
        "realpos": 25,
        "icon_desc_color": "#ff3852",
        "topic_flag": 0,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 24
      },
      {
        "note": "胡明轩",
        "ad_info": "",
        "category": "体育",
        "num": 524861,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "4793417383285601",
        "word": "胡明轩",
        "fun_word": 0,
        "flag": 1,
        "onboard_time": 1658324374,
        "raw_hot": 1743612,
        "emoticon": "",
        "word_scheme": "#胡明轩#",
        "star_name": {},
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "",
        "icon_desc": "新",
        "realpos": 26,
        "icon_desc_color": "#ff3852",
        "topic_flag": 1,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 25
      },
      {
        "note": "男子果断扔手机张开双臂接坠楼幼童",
        "ad_info": "",
        "category": "社会正能量",
        "num": 523539,
        "expand": 0,
        "mid": "4793428096057365",
        "word": "男子果断扔手机张开双臂接坠楼幼童",
        "emoticon": "",
        "label_name": "",
        "raw_hot": 523539,
        "subject_label": "",
        "flag": 0,
        "subject_querys": "",
        "star_name": {},
        "channel_type": "",
        "word_scheme": "#男子果断扔手机张开双臂接坠楼幼童#",
        "realpos": 27,
        "onboard_time": 1658320472,
        "topic_flag": 1,
        "fun_word": 0,
        "star_word": 0,
        "rank": 26
      },
      {
        "note": "毒贩下药迷晕多名男性朋友实施猥亵",
        "ad_info": "",
        "category": "社会新闻",
        "num": 503621,
        "expand": 0,
        "mid": "4793236180963284",
        "word": "毒贩下药迷晕多名男性朋友实施猥亵",
        "emoticon": "",
        "label_name": "",
        "raw_hot": 503621,
        "subject_label": "",
        "flag": 0,
        "subject_querys": "",
        "star_name": {},
        "channel_type": "",
        "word_scheme": "#毒贩下药迷晕多名男性朋友实施猥亵#",
        "realpos": 28,
        "onboard_time": 1658311295,
        "topic_flag": 1,
        "fun_word": 0,
        "star_word": 0,
        "rank": 27
      },
      {
        "note": "微信支持全屏输入",
        "ad_info": "",
        "category": "科技",
        "num": 438847,
        "expand": 0,
        "mid": "4793399258909132",
        "word": "微信支持全屏输入",
        "emoticon": "",
        "label_name": "",
        "raw_hot": 438847,
        "subject_label": "",
        "flag": 0,
        "subject_querys": "",
        "star_name": {},
        "channel_type": "",
        "word_scheme": "#微信支持全屏输入#",
        "realpos": 29,
        "onboard_time": 1658321674,
        "topic_flag": 1,
        "fun_word": 0,
        "star_word": 0,
        "rank": 28
      },
      {
        "note": "接坠楼幼童男子说救人出于父亲本能",
        "ad_info": "",
        "category": "社会新闻",
        "num": 421341,
        "expand": 0,
        "mid": "4793392346696856",
        "word": "接坠楼幼童男子说救人出于父亲本能",
        "emoticon": "",
        "label_name": "",
        "raw_hot": 421341,
        "subject_label": "",
        "flag": 0,
        "subject_querys": "",
        "star_name": {},
        "channel_type": "",
        "word_scheme": "#接坠楼幼童男子说救人出于父亲本能#",
        "realpos": 30,
        "onboard_time": 1658324133,
        "topic_flag": 1,
        "fun_word": 0,
        "star_word": 0,
        "rank": 29
      },
      {
        "note": "杨紫颜淡三大美德",
        "ad_info": "",
        "category": "影视",
        "num": 418058,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "fun_word": 1,
        "mid": "4793411422657057",
        "word": "杨紫颜淡三大美德",
        "flag": 1,
        "onboard_time": 1658325393,
        "flag_desc": "剧集",
        "word_scheme": "#杨紫颜淡三大美德#",
        "emoticon": "[心]",
        "star_name": [
          "杨紫"
        ],
        "is_new": 1,
        "subject_label": "剧集",
        "raw_hot": 606752,
        "subject_querys": "剧集|沉香如屑",
        "label_name": "新",
        "channel_type": "Entertainment",
        "icon_desc": "新",
        "realpos": 31,
        "icon_desc_color": "#ff3852",
        "topic_flag": 1,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 30
      },
      {
        "note": "何幸福让万传家把刑期当学期",
        "ad_info": "",
        "category": "影视",
        "num": 411566,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "fun_word": 1,
        "mid": "4793379538605175",
        "word": "何幸福让万传家把刑期当学期",
        "flag": 1,
        "onboard_time": 1658326413,
        "flag_desc": "剧集",
        "word_scheme": "#何幸福让万传家把刑期当学期#",
        "emoticon": "",
        "star_name": {},
        "is_new": 1,
        "subject_label": "剧集",
        "raw_hot": 529219,
        "subject_querys": "剧集|幸福到万家",
        "label_name": "新",
        "channel_type": "Entertainment",
        "icon_desc": "新",
        "realpos": 32,
        "icon_desc_color": "#ff3852",
        "topic_flag": 1,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 31
      },
      {
        "note": "沉香如屑 不够看",
        "ad_info": "",
        "category": "影视",
        "num": 409633,
        "expand": 0,
        "mid": "4793393434068273",
        "word": "沉香如屑 不够看",
        "label_name": "",
        "emoticon": "",
        "raw_hot": 530118,
        "flag": 0,
        "flag_desc": "剧集",
        "fun_word": 1,
        "subject_querys": "剧集|沉香如屑",
        "star_name": {},
        "channel_type": "Entertainment",
        "word_scheme": "沉香如屑 不够看",
        "realpos": 33,
        "onboard_time": 1658323713,
        "topic_flag": 0,
        "subject_label": "剧集",
        "star_word": 0,
        "rank": 32
      },
      {
        "note": "中国男篮vs黎巴嫩男篮",
        "ad_info": "",
        "category": "体育",
        "num": 402514,
        "expand": 0,
        "mid": "4793425532554466",
        "word": "中国男篮vs黎巴嫩男篮",
        "label_name": "",
        "fun_word": 0,
        "emoticon": "",
        "flag": 0,
        "discuss_roomid": 11236,
        "subject_label": "",
        "discuss_room_gray": 0,
        "subject_querys": "",
        "star_name": {},
        "channel_type": "",
        "star_word": 0,
        "realpos": 34,
        "onboard_time": 1658322455,
        "topic_flag": 1,
        "raw_hot": 453287,
        "word_scheme": "#中国男篮vs黎巴嫩男篮#",
        "rank": 33
      },
      {
        "note": "王嘉尔直播",
        "ad_info": "",
        "category": "艺人",
        "num": 400001,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "4793411658580202",
        "word": "王嘉尔直播",
        "fun_word": 1,
        "flag": 1,
        "onboard_time": 1658327016,
        "raw_hot": 445791,
        "emoticon": "",
        "word_scheme": "王嘉尔直播",
        "star_name": [
          "王嘉尔"
        ],
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "Entertainment",
        "icon_desc": "新",
        "realpos": 35,
        "icon_desc_color": "#ff3852",
        "topic_flag": 0,
        "small_icon_desc": "新",
        "star_word": 1,
        "rank": 34
      },
      {
        "note": "兰州本轮疫情感染者已超1000例",
        "ad_info": "",
        "category": "社会新闻",
        "num": 396716,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "4793375406688418",
        "word": "兰州本轮疫情感染者已超1000例",
        "fun_word": 0,
        "flag": 1,
        "onboard_time": 1658324854,
        "raw_hot": 396716,
        "emoticon": "",
        "word_scheme": "#兰州本轮疫情感染者已超1000例#",
        "star_name": {},
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "",
        "icon_desc": "新",
        "realpos": 36,
        "icon_desc_color": "#ff3852",
        "topic_flag": 1,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 35
      },
      {
        "note": "徐嘉余家人回应",
        "ad_info": "",
        "category": "体育",
        "num": 374190,
        "expand": 0,
        "mid": "4793378154484586",
        "word": "徐嘉余家人回应",
        "emoticon": "",
        "label_name": "",
        "raw_hot": 374190,
        "subject_label": "",
        "flag": 0,
        "subject_querys": "",
        "star_name": {},
        "channel_type": "",
        "word_scheme": "#徐嘉余家人回应#",
        "realpos": 37,
        "onboard_time": 1658312075,
        "topic_flag": 1,
        "fun_word": 0,
        "star_word": 0,
        "rank": 36
      },
      {
        "note": "蒙犽秒杀皮肤",
        "ad_info": "",
        "category": "游戏",
        "num": 372933,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "4793413843291313",
        "word": "蒙犽秒杀皮肤",
        "fun_word": 0,
        "flag": 1,
        "onboard_time": 1658324734,
        "raw_hot": 372933,
        "emoticon": "",
        "word_scheme": "#蒙犽秒杀皮肤#",
        "star_name": {},
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "",
        "icon_desc": "新",
        "realpos": 38,
        "icon_desc_color": "#ff3852",
        "topic_flag": 1,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 37
      },
      {
        "note": "男子卫生间强拽女子被采取刑事强制措施",
        "ad_info": "",
        "category": "社会新闻",
        "num": 354954,
        "expand": 0,
        "mid": "4793380218079650",
        "word": "男子卫生间强拽女子被采取刑事强制措施",
        "emoticon": "",
        "label_name": "",
        "raw_hot": 354954,
        "subject_label": "",
        "flag": 0,
        "subject_querys": "",
        "star_name": {},
        "channel_type": "",
        "word_scheme": "#男子卫生间强拽女子被采取刑事强制措施#",
        "realpos": 39,
        "onboard_time": 1658308118,
        "topic_flag": 1,
        "fun_word": 0,
        "star_word": 0,
        "rank": 38
      },
      {
        "note": "彩虹",
        "ad_info": "",
        "category": "社会新闻",
        "num": 354942,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "4793422114194022",
        "word": "彩虹",
        "fun_word": 0,
        "flag": 1,
        "onboard_time": 1658327617,
        "raw_hot": 354942,
        "emoticon": "",
        "word_scheme": "彩虹",
        "star_name": {},
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "",
        "icon_desc": "新",
        "realpos": 40,
        "icon_desc_color": "#ff3852",
        "topic_flag": 0,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 39
      },
      {
        "note": "王冰冰朋友圈",
        "ad_info": "",
        "category": "体育,艺人",
        "num": 354677,
        "expand": 0,
        "mid": "4793354817112917",
        "word": "王冰冰朋友圈",
        "emoticon": "",
        "label_name": "",
        "raw_hot": 430108,
        "subject_label": "",
        "flag": 0,
        "subject_querys": "",
        "star_name": {},
        "channel_type": "Entertainment",
        "word_scheme": "#王冰冰朋友圈#",
        "realpos": 41,
        "onboard_time": 1658308956,
        "topic_flag": 1,
        "fun_word": 1,
        "star_word": 1,
        "rank": 40
      },
      {
        "note": "毛俊杰商业版图",
        "ad_info": "",
        "category": "艺人",
        "num": 354073,
        "expand": 0,
        "mid": "4793362219535805",
        "word": "毛俊杰商业版图",
        "emoticon": "",
        "label_name": "",
        "raw_hot": 380994,
        "subject_label": "",
        "flag": 0,
        "subject_querys": "",
        "star_name": [
          "毛俊杰"
        ],
        "channel_type": "Entertainment",
        "word_scheme": "#毛俊杰商业版图#",
        "realpos": 42,
        "onboard_time": 1658320712,
        "topic_flag": 1,
        "fun_word": 1,
        "star_word": 1,
        "rank": 41
      },
      {
        "note": "男篮亚洲杯",
        "ad_info": "",
        "category": "体育",
        "num": 353300,
        "expand": 0,
        "mid": "4793033344422063",
        "word": "男篮亚洲杯",
        "emoticon": "",
        "label_name": "",
        "raw_hot": 353300,
        "subject_label": "",
        "flag": 0,
        "subject_querys": "",
        "star_name": {},
        "channel_type": "",
        "word_scheme": "#男篮亚洲杯#",
        "realpos": 43,
        "onboard_time": 1658319629,
        "topic_flag": 1,
        "fun_word": 0,
        "star_word": 0,
        "rank": 42
      },
      {
        "note": "周琦太累了",
        "ad_info": "",
        "category": "体育",
        "num": 323373,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "",
        "word": "周琦太累了",
        "fun_word": 0,
        "flag": 1,
        "onboard_time": 1658329419,
        "raw_hot": 323373,
        "emoticon": "",
        "word_scheme": "周琦太累了",
        "star_name": {},
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "",
        "icon_desc": "新",
        "realpos": 44,
        "icon_desc_color": "#ff3852",
        "topic_flag": 0,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 43
      },
      {
        "note": "原来买菜也可以很浪漫",
        "ad_info": "",
        "category": "幽默",
        "num": 288567,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "4793403256607027",
        "word": "原来买菜也可以很浪漫",
        "fun_word": 0,
        "flag": 1,
        "onboard_time": 1658326772,
        "raw_hot": 288567,
        "emoticon": "",
        "word_scheme": "#原来买菜也可以很浪漫#",
        "star_name": {},
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "",
        "icon_desc": "新",
        "realpos": 45,
        "icon_desc_color": "#ff3852",
        "topic_flag": 1,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 44
      },
      {
        "note": "女儿的复旦录取通知是妈妈送来的",
        "ad_info": "",
        "category": "社会新闻,教育",
        "num": 262216,
        "expand": 0,
        "mid": "4793376979031185",
        "word": "女儿的复旦录取通知是妈妈送来的",
        "emoticon": "",
        "label_name": "",
        "raw_hot": 262216,
        "subject_label": "",
        "flag": 0,
        "subject_querys": "",
        "star_name": {},
        "channel_type": "",
        "word_scheme": "#女儿的复旦录取通知是妈妈送来的#",
        "realpos": 46,
        "onboard_time": 1658315491,
        "topic_flag": 1,
        "fun_word": 0,
        "star_word": 0,
        "rank": 45
      },
      {
        "note": "赵睿赛前发烧",
        "ad_info": "",
        "category": "体育",
        "num": 233020,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "4793422084312703",
        "word": "赵睿赛前发烧",
        "fun_word": 0,
        "flag": 1,
        "onboard_time": 1658326953,
        "raw_hot": 233020,
        "emoticon": "",
        "word_scheme": "#赵睿赛前发烧#",
        "star_name": {},
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "",
        "icon_desc": "新",
        "realpos": 47,
        "icon_desc_color": "#ff3852",
        "topic_flag": 1,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 46
      },
      {
        "note": "成都疫情防控",
        "ad_info": "",
        "category": "社会新闻",
        "num": 223685,
        "expand": 0,
        "mid": "4793048124886791",
        "word": "成都疫情防控",
        "emoticon": "",
        "label_name": "",
        "raw_hot": 223685,
        "subject_label": "",
        "flag": 0,
        "subject_querys": "",
        "star_name": {},
        "channel_type": "",
        "word_scheme": "成都疫情防控",
        "realpos": 48,
        "onboard_time": 1658312675,
        "topic_flag": 0,
        "fun_word": 0,
        "star_word": 0,
        "rank": 47
      },
      {
        "note": "周琦失误后没人退防",
        "ad_info": "",
        "category": "体育",
        "num": 208231,
        "expand": 0,
        "small_icon_desc_color": "#ff3852",
        "mid": "4793429018546799",
        "word": "周琦失误后没人退防",
        "fun_word": 0,
        "flag": 1,
        "onboard_time": 1658329477,
        "raw_hot": 208231,
        "emoticon": "",
        "word_scheme": "#周琦失误后没人退防#",
        "star_name": {},
        "subject_label": "",
        "is_new": 1,
        "subject_querys": "",
        "label_name": "新",
        "channel_type": "",
        "icon_desc": "新",
        "realpos": 49,
        "icon_desc_color": "#ff3852",
        "topic_flag": 1,
        "small_icon_desc": "新",
        "star_word": 0,
        "rank": 48
      },
      {
        "note": "我可以做你通讯录里的尸体吗",
        "ad_info": "",
        "category": "情感",
        "num": 207677,
        "expand": 0,
        "mid": "4793341718565080",
        "word": "我可以做你通讯录里的尸体吗",
        "emoticon": "",
        "label_name": "",
        "raw_hot": 207677,
        "subject_label": "",
        "flag": 0,
        "subject_querys": "",
        "star_name": {},
        "channel_type": "",
        "word_scheme": "我可以做你通讯录里的尸体吗",
        "realpos": 50,
        "onboard_time": 1658312792,
        "topic_flag": 0,
        "fun_word": 0,
        "star_word": 0,
        "rank": 49
      }
    ]
  }
}
`
	body := new(WeiboTrendingResp)
	if err := json.Unmarshal([]byte(bodyStr), body); err != nil {
		t.Errorf("json unmarshl err: %s", err.Error())
	}
	for _, r := range body.Data.Realtime {
		if r.Word != r.Note {
			t.Errorf("r.Word: %s and r.Note: %s is not equal", r.Word, r.Note)
		}
	}
}
